import { Button } from "@primer/react";
import { CommitCodeModal } from "components/commit-code-modal";
import { useSession } from "next-auth/react";
import { useState } from "react";

const oldCode = `import Head from "next/head";

export default function Home() {
  const breakTheWorld = () => {
    throw new Error("Oh no you broke the world!");
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <button
          onClick={breakTheWorld}
          className="bg-black text-white p-4 font-bold"
        >
          Break the world
        </button>
      </main>
    </div>
  );
}
`;

const newCode = `import Head from "next/head";

export default function Home() {
  const breakTheWorld = () => {
    throw new Error("Oh no you broke the world! You are bad!");
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <button
          onClick={breakTheWorld}
          className="bg-black text-white p-4 font-bold"
        >
          Break the world
        </button>
      </main>
    </div>
  );
}
`;

export default function Test() {
  const { data, status } = useSession({
    required: true,
  });

  const [isOpen, setIsOpen] = useState(false);
  const handleClose = () => {
    setIsOpen(false);
  };

  if (status === "loading") return <p>Loading...</p>;

  return (
    <div className="p-4">
      <Button onClick={() => setIsOpen(true)}>Open Modal</Button>
      <CommitCodeModal
        path="pages/index.js"
        newCode={newCode}
        currentCode={oldCode}
        isOpen={isOpen}
        onClose={handleClose}
        token={data.token as string}
        sha="5b86c5e8e53157f730048166c221a503f0859113"
        repo="sentry-next-example"
        owner="mattrothenberg"
      />
    </div>
  );
}
