name: Deploy to Azure (next-devex-blocks)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: yarn install & build
        run: |
          yarn
          yarn build

      - name: package zip
        run: zip -r web.zip package.json .next node_modules/

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "next-devex-blocks"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: web.zip
